name: Verify code
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install black[python27] isort
      - name: Verify code
        run: |
          black --check -t py27 .
      - name: Verify imports
        run: |
          isort --check packet_helper/ scapy_helper/ test/
